"use strict";

/**
 * Writes public/supabase_config.js from env (Vercel / CI).
 * Uses MENTARIS_SUPABASE_URL + MENTARIS_SUPABASE_ANON_KEY, with NEXT_PUBLIC_* fallbacks.
 * Without env: leaves an existing hand-written file alone; otherwise writes a comment-only stub.
 */

const fs = require("fs");
const path = require("path");

const outPath = path.join(__dirname, "..", "public", "supabase_config.js");

function pick(...candidates) {
  for (const c of candidates) {
    if (typeof c === "string" && c.trim()) return c.trim();
  }
  return "";
}

const url = pick(
  process.env.MENTARIS_SUPABASE_URL,
  process.env.NEXT_PUBLIC_MENTARIS_SUPABASE_URL
);
const anonKey = pick(
  process.env.MENTARIS_SUPABASE_ANON_KEY,
  process.env.NEXT_PUBLIC_MENTARIS_SUPABASE_ANON_KEY,
  process.env.MENTARIS_SUPABASE_PUBLISHABLE_KEY,
  process.env.NEXT_PUBLIC_MENTARIS_SUPABASE_PUBLISHABLE_KEY
);
const table = pick(process.env.MENTARIS_SUPABASE_SCORES_TABLE) || "scores";

const urlNorm = url.replace(/\/+$/, "");

const stub =
  "/* Auto-generated: no Supabase URL+anon key in env at build time. */\n" +
  "/* Set MENTARIS_SUPABASE_URL and MENTARIS_SUPABASE_ANON_KEY on Vercel, or copy supabase_config.example.js. */\n";

if (urlNorm && anonKey) {
  const payload = { url: urlNorm, anonKey, table };
  const body =
    "/* Auto-generated by scripts/write_supabase_config.js — do not edit. */\n" +
    `window.__MENTARIS_SUPABASE__=${JSON.stringify(payload)};\n`;
  fs.writeFileSync(outPath, body, "utf8");
  console.log("Wrote public/supabase_config.js from env.");
} else if (
  fs.existsSync(outPath) &&
  fs.readFileSync(outPath, "utf8").includes("window.__MENTARIS_SUPABASE__")
) {
  console.log("Leaving public/supabase_config.js unchanged (local/manual config, no Supabase env).");
} else {
  fs.writeFileSync(outPath, stub, "utf8");
  console.log("Wrote public/supabase_config.js stub (no Supabase env).");
}
